name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "Minimus registry auth"
      run: docker login -u minimus -p ${{ secrets.MINIMUS_TOKEN }} reg.mini.dev
    - name: Print NODE_SHA
      run: echo ${{ vars.NODE_SHA }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: readonlyrecords/node-app:latest
        build-args: |
          NODESHA=${{ vars.NODE_SHA }}
      
      
