
name: Update NODE_SHA
on: 
  repository_dispatch:
    types: [newImageVersion]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Update the image SHA -- requires a PAT with write access to Action variables.
      # Check that the image name is node and it's not a -dev variant.
      - name: Set NODE_SHA
        if: "github.event.client_payload.imageDetails.name == 'node' && !contains(github.event.client_payload.imageDetails.version, '-dev')"
        env:
          GH_TOKEN: ${{ secrets.REPO_UPDATE_PAT }}
          IMAGE_DIGEST: ${{ github.event.client_payload.imageDetails.digest }}
          IMAGE_REPO: ${{ github.repository }}
        run: |
          gh variable set NODE_SHA --body "$IMAGE_DIGEST" --repo $IMAGE_REPO
      # Now, do -dev
      - name: Set NODE_SHA_DEV
        if: "github.event.client_payload.imageDetails.name == 'node' && contains(github.event.client_payload.imageDetails.version, '-dev')"
        env:
          GH_TOKEN: ${{ secrets.REPO_UPDATE_PAT }}
          IMAGE_DIGEST: ${{ github.event.client_payload.imageDetails.digest }}
          IMAGE_REPO: ${{ github.repository }}
        run: |
          gh variable set NODE_SHA_DEV --body "$IMAGE_DIGEST" --repo $IMAGE_REPO
